//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Scholarship.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StudentId { get; set; }
        public double Cgpa { get; set; }
        public string Dept { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime  DOB { get; set; }
    }
}
